# Site settings
title: Welcome
description: 'Hi Im Phil, a Computer and Network Engineering graduate who spends most of his time building, tinkering and restoring anything electrical or mechanical. Here I will share insightful knowledge and ideas that I have been unable to find an answer to'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Phillip Kaddis'
  email: phillipkaddis@gmail.com
  twitter_username: phillipkaddis
  facebook_username: phillipkaddis
  github_username:  phillipkaddis
  linkedin_username:  phillipkaddis

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
